POST http://localhost:3000/api/meetings/create-meeting/651219a3242f69172053ba34
Content-Type: application/json

{
    "meetingName": "Testing",
    "date": "2023-09-27",
    "time": "2pm",
    "meetingLocation": "Svea",
    "meetingAgenda": "Discuss tests",
}


###